config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  resources :corsairs

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/corsair.rb
class Corsair < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/corsairs_controller.rb
class CorsairsController < ApplicationController

	def index
    @corsairs = Corsair.all
  	end

  	def new
    @corsair = Corsair.new
  	end

  	def create
    @corsair = Corsair.new(corsair_params)
    	if @corsair.save
     		redirect_to corsair_path(@corsair)
    	else
      		render 'new'
    	end
  	end

  	def show
    @corsair = Corsair.find(params[:id])
  	end

  	def edit
    @corsair = Corsair.find(params[:id])
  	end

  	def update
    @corsair = Corsair.find(params[:id])
    new_corsair = corsair_params
    	if @corsair.update(new_corsair)
      		redirect_to corsairs_path
    	else
      		render 'edit'
    	end
  	end

  	def destroy
    @corsair = Corsair.find(params[:id])
    @corsair.destroy
    	redirect_to corsairs_path
  	end


  private

  def corsair_params
    params.require(:corsair).permit(:first_name, :age, :likeness, :bio)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/corsairs_helper.rb
module CorsairsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/corsairs/edit.html.erb
<h1>Edition</h1>

 
<%= form_with(model: @corsair, local: true) do |form| %>
 
 <p>
    <%= form.label :first_name %><br>
    <%= form.text_field :first_name %>
  </p>
 
  <p>
    <%= form.label :age %><br>
    <%= form.text_area :age %>
  </p>
 
  <p>
    <%= form.submit %>
    <%= link_to '⚠️Clique pour détruire⚠️', @corsair, method: :delete %>
  </p>

  
 
<% end %>
 

app/views/corsairs/index.html.erb
<h1>Liste des Corsairs</h1>

<td><%= link_to 'Espace de rédaction', new_corsair_path %></td>

<br/>


<table>
  <tr>
    <th>Prénom</th>
    <th>Age</th>
  </tr>
 
  <% @corsairs.each do |corsair| %>
    <tr>
      <td><%= corsair.first_name %></td>
      <td><%= corsair.age %></td>
      <td><%= link_to 'Show', corsair_path(corsair) %></td>
    </tr>
  <% end %>
</table>

app/views/corsairs/new.html.erb
<h1>Inscrit toi! </h1>

<%= form_with(model: @corsair, local: true) do |form| %>
  
  <p>
    <%= form.label :first_name %><br>
    <%= form.text_field :first_name %>
  </p>
 
  <p>
    <%= form.label :age %><br>
    <%= form.text_area :age %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/corsairs/show.html.erb
<h1>Prenom : <%= @corsair.first_name %></h1>

<p>Age : <%= @corsair.age %></p>

<p>
	<td><%= link_to 'Edition', edit_corsair_path %></td>
	<td><%= link_to 'Retour à la liste', corsairs_path %></td>
</p>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Accueil",   '#' %></li>
        <li><%= link_to "Index des moussaillons",   '#' %></li>
        <li><%= link_to "Nouveau moussaillon", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Moussaillon</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body margin-top: 50px>
  

  	<%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Bienvenue !</h1>
  <h3>
    Ici, tu peux retrouver les moussaillons 🎓
  </h3>
  <%= link_to "Enregistre-toi !", new_corsair_path, class: "btn btn-lg btn-primary" %>
</div>